spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 415595144887-62upgjogeku2h30s5k1a5tc7fatcd8lr.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            client-id: RfGZMlehMyTPTNu5a0lu
            client-secret: lxlJiUq5em
            redirect-uri: http://localhost:8094/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
            client-name: Naver
            provider: naver

          kakao:
            client-id: 60bd2dce4e1dca19f1c8e255abf86a17
            client-secret: j5jiWiuV9fWVwCRJYiKKg5suQE28cH2p
            redirect-uri: http://localhost:8094/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            provider: kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id