server:
  port: 8094

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/springdb2


  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  profiles:
    include: oauth2

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

file.itemImg.path: "E:/fullSaveFiles/item/"




